### ISSUE TITLE
Add KOL style hover text for each skill

### ISSUE THREAD

**Issue by pstalcup** [loathers/greenbox#32]
As seen in the new skills page

**Comment by gausie** [comment]
Oh interesting. I think that's probably hard to do without the user being logged in - we don't have access to that info, though we could try to scrape it from the wiki that's probably not a great idea

**Comment by docrostov** [comment]
i wonder if any of the ways we snag descriptions for oaf would be usable here?

**Comment by gausie** [comment]
Ok I fucking did this like a mug. It is *ok*. There are better ways we could do it. The key brittle area right now is I'm using some random CORS proxy I found online because the wiki's API does not send CORS headers like it should. To fix this we either need to:

- Get Coldfront to configure the wiki api correctly (I have no idea how to get in contact with the person who runs it because we could really tidy it up quite a lot honestly).
- Write and host our own CORS proxy so you can go to like `https://wikiapi.loathers.net/?<STUFF THAT GETS PROXIED TO api.php ON THE WIKI>` and get the responses with the appropriate CORS headers. @phillammon is probably someone who has sufficient knowhow as to do that if he so chose to.

**Comment by gausie** [comment]
I did step 2 because I'm clearly a mug. Marking as done
